### ISSUE TITLE
New App Creation failing.

### ISSUE THREAD

**Issue by NikkiDreams** [mattma/ember-rocks#11]
I just installed EMRocks today. I have tried creating a new app  a few times but it's not happy with Bluebird?

[16:47:43] [-log:] Starting to generate an application at /www/5movez_app
[16:47:43] [-done:] A new Ember.js mvc application have been successfully created!
[16:47:43] [-done:] A new Node.js web server have been successfully created!
[16:47:43] [-log:] It may take up to 1 minute and half!
[16:47:43] [-log:] Be patient, fetching packages from internet ...
[16:47:43] [-log:] NPM is installing node packages...
[16:47:43] [-log:] Bower is installing javascript packages...
[16:47:43] [-log:] em-cli is doing REALLY hard to initialize your repo ...
Possibly unhandled TypeError: undefined is not a function
    at /usr/local/lib/node_modules/ember-rocks/src/commands/create.js:166:7
    at tryCatcher (/usr/local/lib/node_modules/ember-rocks/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/ember-rocks/node_modules/bluebird/js/main/promise.js:466:31)
    at Promise._settlePromiseAt (/usr/local/lib/node_modules/ember-rocks/node_modules/bluebird/js/main/promise.js:545:18)
    at Promise._settlePromises (/usr/local/lib/node_modules/ember-rocks/node_modules/bluebird/js/main/promise.js:661:14)
    at Async._drainQueue (/usr/local/lib/node_modules/ember-rocks/node_modules/bluebird/js/main/async.js:79:16)
    at Async._drainQueues (/usr/local/lib/node_modules/ember-rocks/node_modules/bluebird/js/main/async.js:89:10)
    at Async.drainQueues (/usr/local/lib/node_modules/ember-rocks/node_modules/bluebird/js/main/async.js:14:14)
    at process._tickCallback (node.js:419:13)

**Comment by mattma** [comment]
Could you do those three commands below and reply the output, please?
Insert it one at the time. 

```bash
bower --version
npm --version
git --version
```

**Comment by NikkiDreams** [comment]
Sorry I totally forgot the env info. I suspect my environment is too up-to-date. I installed ember-Cli as well and I am having problems with that too.  BTW this is a great project. I am much more of a Gulp fan as well.

OSX Yosemite 10.10.2 
$ bower --version 1.3.12
$ npm --version 2.5.1
$ git --version 2.2.2

**Comment by mattma** [comment]
Thanks for the info. It seems all up-to-date. 

The current code base works for me and tested on several different OS, it all works. Let me dive in deeper with it. I may give you more hints what could possibly go wrong. 

Broccoli is an awesome project. Do not get me wrong. I am a big fan of gulp too. Since I do not have to support the whole nine yard of Ember.js group like the purpose of EmberCli does. I could roll out the features more quickly and frequently.

**Comment by NikkiDreams** [comment]
No worries. I am happy to test things. I am going to continue debugging my system and see what weirdness I can find as well.

**Comment by mattma** [comment]
`I installed ember-Cli as well and I am having problems with that too.`

Have you tried to run `ember new myApp` via `Ember-CLI` project. What errors do you get? The same thing like `Bluebird` issue?

You have the latest greatest technologies of all. All your modules are up to dates.

**Comment by mattma** [comment]
Maybe try `sudo em new myApp`. It may related to the permission issues. Since some node modules requires to install `bin` file so it may need a right permission. 

I doubted that is the right problem, but it worths to try.

**Comment by NikkiDreams** [comment]
Yes I have tried sudo... same problem.
ember-cli is a whole different set of problems. It generates almost
everything but the build and install keeps getting stuck on peerDependency
issues. I did a clean install of Node today but still weird things.

**Comment by mattma** [comment]
How about try [io.js](https://iojs.org/en/index.html) instead of `node.js`. After install, it would replace `node` executable. It is basically `node` 1.0

**Comment by NikkiDreams** [comment]
I will give that a try and get back to ya.

**Comment by mattma** [comment]
Sounds good. Good Luck!

**Comment by NikkiDreams** [comment]
GOOD NEWS! 
I wiped node and all it's little babies from my system completely.
I ran DiskUtil and fixed any permissions issues.
I installed HomeBrew and then used HB to install Node.
Fixed another permission collision at /usr/local

Installed Ember Rocks \m/

Annnnnnd theeeeeeeeennnnn...

![screen shot 2015-02-10 at 4 53 49 pm](https://cloud.githubusercontent.com/assets/1399736/6139854/92d1c882-b145-11e4-9546-c377debb3f0f.png)

Thank you for your help and suggestions. 
Nix is one happy girl now!

**Comment by mattma** [comment]
I am glad that you got everything figured out. But The screen shot that you provide here is not what initial screen looks like. I believe that you need to install `sass` to pre-compile your stylesheet to `css`. To do that, you need run `gem install sass`, once you have [sass](http://sass-lang.com/) installed in your system. 

Ember rocks will take over it and live reload on every single `sass` changes you made on your connected browsers. `em serve` will basically do all the development monitoring for `sass` pre compile, es6 pre-compile, hbs, etc, Basically, all your development workflow would be monitored and live reload with very efficient LR server. 

Here is what the initial screen should look like once you compile your `sass` code. And it is responsive and ready for mobile as well. I actually look `sass` over `less` and `stylus`. That is why I am pretty opinion about this. 

![screen shot 2015-02-10 at 9 52 17 pm](https://cloud.githubusercontent.com/assets/1148428/6142658/31447450-b16f-11e4-9ee2-78a02ceec2c3.png)

**Comment by NikkiDreams** [comment]
I missed the SASS install when I wiped my dev environment. Got it now and works like a charm. I am a total n00b using Ember and I am very specific about the tooling of my projects. Ember-Rocks fit all the right needs and amazingly I already have the start of a WebRTC app I am building for a client. Thanks. Keep up the good work! 
\m/

**Comment by mattma** [comment]
Thanks. Could you also shout out the project in Ember community when you have chances?

Hopefully this project could be supported by Ember core team. `Ember-app-kit` supports `grunt`, `Ember-cli` supports `broccoli`, `gulp` is one of the most popular build tools out there but it is indeed missing the love from Ember core team.

**Comment by NikkiDreams** [comment]
I will definitely give the project it's propers in the community.

**Comment by mattma** [comment]
Thanks. :+1:
